const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';

export {
    SET_CURRENT_USER,
    SIGN_UP_ERRORS,
    DELETE_ERROR_MESSAGE,
    SOCIAL_LOGIN_ERROR
};